### ISSUE TITLE
Tile-Based Front-end

### ISSUE THREAD

**Issue by MariaR001** [MariaR001/KPI-DASHBOARD#1]
As a user, I want to have a customizable dashboard so that I can edit it and display as many tiles as I need for information.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must | High | 8 |

## Acceptance Criteria
- The dashboard should be tile-based, displaying data widgets
- Users can control the grid size by dragging the bottom right corners
- Users can resize the tiles in the dashboard
- Users can add new tiles to the dashboard
- Users can remove tiles from the dashboard
- Users can move tiles from the dashboard

## Risks
- Large number or large sizes of grids/tiles could affect performance
- The dashboard should be responsive to different screen sizes

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US

## Tasks
- [x] Use the react-grid-layout library for draggable and resizable tiles
- [x] Implement a basic tile structure
- [x] Implement options for users to control the grid size
- [x] Implement options for users to add and remove tiles
