### ISSUE TITLE
Import and Implement kpi-dash into PostGoat

### ISSUE THREAD

**Issue by MariaR001** [MariaR001/KPI-DASHBOARD#10]
As an application user, I want to import KPI dashboard frontend library and implement it into UInnovate/PostGoat.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must | High | 8 |

## Acceptance Criteria
- The KPI dashboard package is imported
- The KPI dashboard is implemented and works as expected in PostGoat tool

## Risks
- Configuring the project for npm package distribution could be challenging
- Managing versions and backward compatibility is critical
- The documentation must be clear and complete

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US

## Tasks
- [ ] Import library component
- [ ] Implement it as custom view
