### ISSUE TITLE
Publish the frontend library as a react component

### ISSUE THREAD

**Issue by MariaR001** [MariaR001/KPI-DASHBOARD#3]
As an application user, I want the KPI dashboard frontend library to be a react component so I can easily import it in my code.

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must | High | 8 |

## Acceptance Criteria
- The KPI dashboard should be packaged and published as a standalone React component
- The npm package should be easily installable using npm commands
- The component should be configurable/customizable through React props
- Documentation should be provided for installing/importing the component

## Risks
- Configuring the project for npm package distribution could be challenging
- Managing versions and backward compatibility is critical
- The documentation must be clear and complete

## Pre-requisites
- [x] Meet with the stakeholder to clarify the requirements
- [x] Complete the requirements of this US

## Tasks
- [x] Configure the project to be publishable
- [x] Define a versioning strategy
- [x] Ensure the component can be easily customized through props
- [ ] Update the README file to explain the changes

**Comment by MariaR001** [comment]
done!
