### ISSUE TITLE
Storing dashboard configuration in an object

### ISSUE THREAD

**Issue by MariaR001** [MariaR001/KPI-DASHBOARD#4]
As an application user, I want the dashboard configuration to be easily storable, modifiable and persistent through an object allowing seamless integration with data sources

| MoSCoW      |  Risk               | Story Points  |
| ------------- |------------- | ------------- |
| Must | Very High | 13 |

## Acceptance Criteria
- There should be a single object in the frontend that holds all necessary configurations for the dashboard
- The configurations should include grid size, tile type, grid positioning, data source association
- Modifications to any configuration should update the object
- The object should be able to call an endpoint to store itself as a string
- On bootup, the object should be able to load itself from the stored string

## Risks
- Storing configuration could include sensitive information
- Dependency on an endpoint could introduce issues if the endpoint is unavailable
- Complexity can easily increase with varying configuration types and associations

## Tasks
- [x] Design a single object that stores all the required configurations for the dashboard (possibly a .yml)
- [x] Identify and define the different types of configurations
- [x] Implement the mechanism that modifies the config object based on user interaction
- [x] Develop a function to load the config object from the stored string on bootup
- [x] Develop a function to store the object as a string by calling an endpoint
- [x] Develop an error handling mechanism in case the config can't be modified or loaded properly

**Comment by MariaR001** [comment]
done!
